export const PRIMENGCONFIG = {
  addRule: 'Agregar regla',
  removeRule: 'Remover regla',
  startsWith: 'Comienza con',
  contains: 'Contiene',
  notContains: 'No contiene',
  endsWith: 'Termina con',
  equals: 'Es igual',
  notEquals: 'No es igual',
  noFilter: 'Sin filtro',
  clear: 'Limpiar',
  today: 'Hoy',
  matchAll: 'Coincidir con todos',
  matchAny: 'Coincidir con cualquiera',
  apply: 'Aplicar',
  emptySearchMessage: 'No se han encontrado resultados',
  emptyFilterMessage: 'No se han encontrado resultados',
  monthNames: [
    'Enero',
    'Febrero',
    'Marzo',
    'Abril',
    'Mayo',
    'Junio',
    'Julio',
    'Agosto',
    'Septiembre',
    'Octubre',
    'Noviembre',
    'Diciembre',
  ],
  monthNamesShort: [
    'Ene',
    'Feb',
    'Mar',
    'Abr',
    'May',
    'Jun',
    'Jul',
    'Ago',
    'Sep',
    'Oct',
    'Nov',
    'Dic',
  ],
  dayNames: [
    'Domingo',
    'Lunes',
    'Martes',
    'Miércoles',
    'Jueves',
    'Viernes',
    'Sábado',
  ],
  dayNamesShort: ['dom', 'lun', 'mar', 'mié', 'jue', 'vie', 'sáb'],
  dayNamesMin: ['D', 'L', 'M', 'X', 'J', 'V', 'S'],
  dateIs: 'La fecha es',
  dateIsNot: 'La fecha no es',
  dateBefore: 'La fecha es antes de',
  dateAfter: 'La fecha es después de',
};
